// <auto-generated />
using System;
using ControlCatedratico.Connection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControlCatedratico.Migrations
{
    [DbContext(typeof(Conn))]
    [Migration("20211113050640_ControlCatedraticoA")]
    partial class ControlCatedraticoA
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CatedraticoModelCursosModel", b =>
                {
                    b.Property<int>("CatedraticoModelsCodigoCatedratico")
                        .HasColumnType("int");

                    b.Property<int>("CursosModelsCodigoCurso")
                        .HasColumnType("int");

                    b.HasKey("CatedraticoModelsCodigoCatedratico", "CursosModelsCodigoCurso");

                    b.HasIndex("CursosModelsCodigoCurso");

                    b.ToTable("CatedraticoModelCursosModel");
                });

            modelBuilder.Entity("ControlCatedratico.Models.CatedraticoModel", b =>
                {
                    b.Property<int>("CodigoCatedratico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CorreoCatedratico")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.Property<string>("EstadoCatedratico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.Property<int>("NoDpi")
                        .HasColumnType("int");

                    b.Property<string>("NombreCatedratico")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.Property<string>("TelCatedratico")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.HasKey("CodigoCatedratico");

                    b.ToTable("tbl_RegistroCatedratico");
                });

            modelBuilder.Entity("ControlCatedratico.Models.CursosModel", b =>
                {
                    b.Property<int>("CodigoCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CodigoCatedratico")
                        .HasColumnType("int");

                    b.Property<string>("EstadoCurso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFinaliza")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("DATETIME");

                    b.Property<string>("NombreCurso")
                        .IsRequired()
                        .HasColumnType("varchar(35)");

                    b.HasKey("CodigoCurso");

                    b.ToTable("tbl_RegistroCursos");
                });

            modelBuilder.Entity("CatedraticoModelCursosModel", b =>
                {
                    b.HasOne("ControlCatedratico.Models.CatedraticoModel", null)
                        .WithMany()
                        .HasForeignKey("CatedraticoModelsCodigoCatedratico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlCatedratico.Models.CursosModel", null)
                        .WithMany()
                        .HasForeignKey("CursosModelsCodigoCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
